.TH "Referência do diretório include" 3 "Terça, 10 de Junho de 2014" "Version 1.0.x" "captura" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referência do diretório include \- 
.SH SYNOPSIS
.br
.PP
.SS "Arquivos"

.in +1c
.ti -1c
.RI "arquivo \fBaacdata\&.h\fP"
.br
.ti -1c
.RI "arquivo \fBconnect\&.h\fP"
.br
.ti -1c
.RI "arquivo \fBlogger\&.h\fP"
.br
.ti -1c
.RI "arquivo \fBparser\&.h\fP"
.br
.ti -1c
.RI "arquivo \fBqueue\&.h\fP"
.br
.ti -1c
.RI "arquivo \fBrawdata\&.h\fP"
.br
.ti -1c
.RI "arquivo \fBthreadpool\&.h\fP"
.br
.in -1c
