.TH "Referência do diretório src" 3 "Terça, 10 de Junho de 2014" "Version 1.0.x" "captura" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referência do diretório src \- 
.SH SYNOPSIS
.br
.PP
.SS "Arquivos"

.in +1c
.ti -1c
.RI "arquivo \fBaacdata\&.cpp\fP"
.br
.ti -1c
.RI "arquivo \fBconnect\&.cpp\fP"
.br
.ti -1c
.RI "arquivo \fBlogger\&.cpp\fP"
.br
.ti -1c
.RI "arquivo \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "arquivo \fBparser\&.cpp\fP"
.br
.ti -1c
.RI "arquivo \fBqueue\&.cpp\fP"
.br
.ti -1c
.RI "arquivo \fBrawdata\&.cpp\fP"
.br
.ti -1c
.RI "arquivo \fBthreadpool\&.cpp\fP"
.br
.in -1c
