.TH "ConnectionClosedException" 3 "Terça, 10 de Junho de 2014" "Version 1.0.x" "captura" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConnectionClosedException \- 
.PP
Exceção ocorre quando se tenta acessar informações da conexão e/ou codec sem ter aberto a conexão\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <connect\&.h>\fP
.PP
Herdeiro de ConnectException\&.
.SH "Descrição Detalhada"
.PP 
Exceção ocorre quando se tenta acessar informações da conexão e/ou codec sem ter aberto a conexão\&. 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para captura a partir de seu código-fonte\&.
