.TH "ConnectException" 3 "Terça, 10 de Junho de 2014" "Version 1.0.x" "captura" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConnectException \- 
.PP
Classe para conexão com streams\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <connect\&.h>\fP
.PP
Herdeiro de exception e exception\&.
.SH "Descrição Detalhada"
.PP 
Classe para conexão com streams\&. 

abre uma conexão com um stream via FFMPEGinclusão dos headers FFMPEG Exceção base de conexão estrutura usada para indicar que houve uma exceção de conexão 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para captura a partir de seu código-fonte\&.
