.TH "Logger" 3 "Terça, 10 de Junho de 2014" "Version 1.0.x" "captura" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Logger \- 
.SH SYNOPSIS
.br
.PP
.SS "Métodos Públicos"

.in +1c
.ti -1c
.RI "\fBLogger\fP ()"
.br
.ti -1c
.RI "virtual \fB~Logger\fP ()"
.br
.in -1c
.SH "Construtores & Destrutores"
.PP 
.SS "Logger::Logger ()"
Default constructor 
.SS "Logger::~Logger ()\fC [virtual]\fP"
Default destructor 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para captura a partir de seu código-fonte\&.
