.TH "MediaTypeNoAudioException" 3 "Terça, 10 de Junho de 2014" "Version 1.0.x" "captura" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MediaTypeNoAudioException \- 
.PP
Exceção ocorre quando na conexão não for identificado nenhum stream de audio, o que nesta versão não é suportado\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <connect\&.h>\fP
.PP
Herdeiro de ConnectException\&.
.SH "Descrição Detalhada"
.PP 
Exceção ocorre quando na conexão não for identificado nenhum stream de audio, o que nesta versão não é suportado\&. 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para captura a partir de seu código-fonte\&.
