.TH "Queue" 3 "Terça, 10 de Junho de 2014" "Version 1.0.x" "captura" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Queue \- 
.SH SYNOPSIS
.br
.PP
.SS "Métodos Públicos"

.in +1c
.ti -1c
.RI "\fBQueue\fP ()"
.br
.ti -1c
.RI "virtual \fB~Queue\fP ()"
.br
.in -1c
.SH "Construtores & Destrutores"
.PP 
.SS "Queue::Queue ()"
Default constructor 
.SS "Queue::~Queue ()\fC [virtual]\fP"
Default destructor 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para captura a partir de seu código-fonte\&.
