.TH "RAWData" 3 "Terça, 10 de Junho de 2014" "Version 1.0.x" "captura" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RAWData \- 
.SH SYNOPSIS
.br
.PP
.SS "Métodos Públicos"

.in +1c
.ti -1c
.RI "\fBRAWData\fP ()"
.br
.ti -1c
.RI "virtual \fB~RAWData\fP ()"
.br
.in -1c
.SH "Construtores & Destrutores"
.PP 
.SS "RAWData::RAWData ()"
Default constructor 
.SS "RAWData::~RAWData ()\fC [virtual]\fP"
Default destructor 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para captura a partir de seu código-fonte\&.
