.TH "StreamType" 3 "Terça, 10 de Junho de 2014" "Version 1.0.x" "captura" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StreamType \- 
.PP
Estrutura que representa os streams de uma conexão\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <connect\&.h>\fP
.SS "Atributos Públicos"

.in +1c
.ti -1c
.RI "unsigned int \fBid\fP"
.br
.ti -1c
.RI "AVMediaType \fBstreamType\fP"
.br
.in -1c
.SH "Descrição Detalhada"
.PP 
Estrutura que representa os streams de uma conexão\&. 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para captura a partir de seu código-fonte\&.
